## MPD CONFIGURATION FOR BLACKROZ
## create by null@2026

music_directory         "/home/music/repo/"
playlist_directory      "/home/music/.config/mpd/playlists"
log_file                "syslog"
pid_file                "/home/music/.config/mpd/mpd.pid"
state_file              "/home/music/.config/mpd/mpd.state"
sticker_file            "/home/music/.config/mpd/mpd.sticker"
#group                   "audio"
bind_to_address         "any"
port                    "6600"
log_level               "default"
auto_update             "yes"

database {
        plugin "simple"
        path "/home/music/.config/mpd/mpd.db"
}

audio_output {
        type            "pulse"
        name            "Pulse"
#        auto_format     "no"
#        auto_channels   "no"
#        auto_resample   "no"
}
